@startuml Antep

class TkinterMapView{
    +pack(int, int)
    +set_position(int, int)
    +set_zoom(int)
}


class Marker{
    +get(str)
    +set_marker(int, int)
}


class Button{
    +get(strt)
    +buscar(set_marker())
    +limpiar(delete())
    +place(int, int)
}


class Root{
    +title(str)
    +geometry(str)
    +resizable(int, int)
    +pack(int, int)
}

class ttk{
    +Combobox(state, values)
    +place(int, int)
}

class Label{
    +place(int, int)
}

class Tkinter{

}


Tkinter <-- Label
Tkinter <- Root
Tkinter <-- Button
Marker <- TkinterMapView
TkinterMapView <-- Root

@enduml 
